server:
  host: 0.0.0.0
  port: 8080
kafka:
  host: localhost
  port: 9092
  domain: example-domain
  keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
  valueDeserializer: io.vertx.kafka.client.serialization.JsonObjectDeserializer
  consumerGroupId: example_group
  offsetReset: earliest
  autoCommit: true
  topics:
    userUpdated: user-updated
